services:
  web:
    build: ./hello_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./hello_django/.env.dev